spring.application.name=careerlens-backend

# Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-shy-waterfall-b4fb5473-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_R4ngiYUs7THb
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080